#!/usr/bin/python3
# -*- coding: utf-8 -*-

import shutil
from pathlib import Path
import os

if __name__ == "__main__":
    share_dir = Path.home() / ".local/share/cpp_atcoder_template"
    bin_dir = Path.home() / (".local/bin")
    if not share_dir.exists():
        os.mkdir(share_dir)
    shutil.copy("./template.cc", share_dir)
    shutil.copy("./atcoder", bin_dir)
